version: '3.8'

services:
  app:
    build: .
    container_name: courier-tracking-app
    depends_on:
      - db
      - redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/courier_tracking
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    ports:
      - "8080:8080"
    restart: always

  db:
    image: postgres:15
    container_name: courier-tracking-db
    environment:
      POSTGRES_DB: courier_tracking
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: courier-tracking-redis
    ports:
      - "6379:6379"
    restart: always

volumes:
  postgres_data:
